<?php

namespace Database\Seeders;

use App\Models\AiQuickAction;
use Illuminate\Database\Seeder;

class AiQuickActionSeeder extends Seeder
{
    public function run(): void
    {
        AiQuickAction::truncate();

        $actions = [
            // ═══════════════════════════════════════════════════════════════
            //  LANGUAGE-SPECIFIC — available to ALL roles
            // ═══════════════════════════════════════════════════════════════
            ['role' => null, 'language' => null, 'type' => 'quick_action', 'icon' => 'translate',  'label' => 'English',       'prompt' => 'Please respond in English.', 'sort_order' => 1, 'is_active' => true],
            ['role' => null, 'language' => null, 'type' => 'quick_action', 'icon' => 'translate',  'label' => 'العربية',       'prompt' => 'الرجاء الرد باللغة العربية.', 'sort_order' => 1, 'is_active' => true],
            ['role' => null, 'language' => null, 'type' => 'quick_action', 'icon' => 'translate',  'label' => 'اردو',          'prompt' => 'براہ کرم اردو میں جواب دیں۔', 'sort_order' => 1, 'is_active' => true],
            ['role' => null, 'language' => null, 'type' => 'quick_action', 'icon' => 'translate',  'label' => 'Euskara',       'prompt' => 'Mesedez, erantzun euskaraz.', 'sort_order' => 1, 'is_active' => true],

            // ═══════════════════════════════════════════════════════════════
            //  ADMIN (12)
            // ═══════════════════════════════════════════════════════════════
                        ['role' => 'Admin', 'language' => 'en', 'type' => 'quick_action', 'icon' => 'dashboard',             'label' => 'Platform Pulse',               'prompt' => 'Give me a real-time platform pulse: total users, active animals today, new registrations this week, pending approvals count, and any anomalies requiring immediate attention.', 'sort_order' => 2, 'is_active' => true],
            ['role' => 'Admin', 'language' => 'en', 'type' => 'quick_action', 'icon' => 'approval',              'label' => 'Approval Queue',               'prompt' => 'Walk me through every item in my approval queue — draft auctions, pending transfers, flagged content, and reported users. Give me a summary with actionable recommendations for each.', 'sort_order' => 3, 'is_active' => true],
            ['role' => 'Admin', 'language' => 'en', 'type' => 'quick_action', 'icon' => 'trending_up',           'label' => 'Growth Trends',                'prompt' => 'Analyze user growth, animal registration trends, and platform engagement over the last 30 days. Highlight spikes, dips, and patterns and suggest what might be causing them.', 'sort_order' => 4, 'is_active' => true],
            ['role' => 'Admin', 'type' => 'quick_action', 'icon' => 'account_balance',       'label' => 'Revenue Deep Dive',            'prompt' => 'Break down this month\'s revenue by source (subscriptions, auction commissions, transfer fees) and compare to last month and same month last year. Flag any anomalies or unexpected changes.', 'sort_order' => 4, 'is_active' => true],
            ['role' => 'Admin', 'type' => 'quick_action', 'icon' => 'bug_report',            'label' => 'System Health',                'prompt' => 'Check for system issues: devices with no recent ping, failed payment retries, queue job failures, and any warnings in recent system activity. Prioritize issues by severity.', 'sort_order' => 5, 'is_active' => true],
            ['role' => 'Admin', 'type' => 'quick_action', 'icon' => 'supervisor_account',    'label' => 'Staff Performance',            'prompt' => 'Give me a performance overview of support and customer service staff: tickets resolved, average response time, customer satisfaction indicators, and workload distribution.', 'sort_order' => 6, 'is_active' => true],
            ['role' => 'Admin', 'type' => 'quick_action', 'icon' => 'diversity_3',           'label' => 'User Demographics',            'prompt' => 'Analyze the platform user base by role distribution, geographic spread, subscription tier, and activity level. Identify any segments that are growing or shrinking.', 'sort_order' => 7, 'is_active' => true],
            ['role' => 'Admin', 'type' => 'quick_action', 'icon' => 'receipt_long',          'label' => 'Commission Audit',             'prompt' => 'Generate an audit report of all commissions from the past 30 days: collected vs pending, by type (auction vs transfer), with amounts and responsible parties.', 'sort_order' => 8, 'is_active' => true],
            ['role' => 'Admin', 'type' => 'quick_action', 'icon' => 'report_problem',        'label' => 'Risk Assessment',              'prompt' => 'Identify high-risk areas: accounts with failed payments, disputed auctions, animals with unresolved health alerts for over 7 days, and users with multiple rejected listings.', 'sort_order' => 9, 'is_active' => true],
            ['role' => 'Admin', 'type' => 'quick_action', 'icon' => 'campaign',              'label' => 'Engagement Audit',             'prompt' => 'Which platform features have the lowest engagement? Analyze feature usage data and suggest three specific actions to improve adoption of underutilized features.', 'sort_order' => 10, 'is_active' => true],
            ['role' => 'Admin', 'type' => 'quick_action', 'icon' => 'assignment',            'label' => 'Weekly Ops Brief',             'prompt' => 'Generate a concise weekly operations briefing covering: new users, active auctions, completed transfers, revenue, pending issues, and key metrics changes week-over-week.', 'sort_order' => 11, 'is_active' => true],
            ['role' => 'Admin', 'type' => 'quick_action', 'icon' => 'database_sync',         'label' => 'Device Fleet Status',          'prompt' => 'Analyze the entire device fleet: online vs offline ratio, battery levels distribution, devices with no GPS ping in 24h, and models nearing end of life.', 'sort_order' => 12, 'is_active' => true],

            // ═══════════════════════════════════════════════════════════════
            //  SUPPORT (10)
            // ═══════════════════════════════════════════════════════════════
            ['role' => 'Support', 'type' => 'quick_action', 'icon' => 'priority_high',       'label' => 'Priority Queue',               'prompt' => 'Show me all open tickets sorted by priority, highlighting anything escalated or waiting more than 4 hours for a first response.', 'sort_order' => 1, 'is_active' => true],
            ['role' => 'Support', 'type' => 'quick_action', 'icon' => 'person_search',       'label' => 'User Lookup',                  'prompt' => 'Help me look up a user account. I will provide a name, email, or ID. Once found, summarize their account status, recent activity, and any open tickets.', 'sort_order' => 2, 'is_active' => true],
            ['role' => 'Support', 'type' => 'quick_action', 'icon' => 'trending_flat',       'label' => 'Ticket Patterns',              'prompt' => 'Analyze ticket patterns this week: which topics are spiking, which users are repeat reporters, and what root causes are emerging. Suggest proactive solutions.', 'sort_order' => 3, 'is_active' => true],
            ['role' => 'Support', 'type' => 'quick_action', 'icon' => 'timer_off',           'label' => 'SLA Breach Watch',             'prompt' => 'List all tickets approaching or breaching SLA thresholds, sorted by urgency. Include ticket age, last activity, and assignee.', 'sort_order' => 4, 'is_active' => true],
            ['role' => 'Support', 'type' => 'quick_action', 'icon' => 'auto_awesome',        'label' => 'Draft Response',               'prompt' => 'Help me draft a professional response to a user. I will outline the issue and I need a clear, empathetic reply that addresses their concern and provides next steps.', 'sort_order' => 5, 'is_active' => true],
            ['role' => 'Support', 'type' => 'quick_action', 'icon' => 'summarize',           'label' => 'Ticket Summary',               'prompt' => 'Summarize the ticket I\'m currently viewing. Extract: issue type, user account age, steps already taken, and suggested next action.', 'sort_order' => 6, 'is_active' => true],
            ['role' => 'Support', 'type' => 'quick_action', 'icon' => 'group_work',          'label' => 'Knowledge Search',             'prompt' => 'I need to find the right procedure or documentation for a common user issue. Help me search the platform\'s help resources and summarize the relevant solution.', 'sort_order' => 7, 'is_active' => true],
            ['role' => 'Support', 'type' => 'quick_action', 'icon' => 'feedback',            'label' => 'Escalation Helper',            'prompt' => 'I need to escalate a ticket. Help me draft a clear escalation note that includes: the issue summary, what has been tried, why escalation is needed, and recommended next steps.', 'sort_order' => 8, 'is_active' => true],
            ['role' => 'Support', 'type' => 'quick_action', 'icon' => 'speed',               'label' => 'My Stats',                     'prompt' => 'Show my personal support metrics: tickets resolved today and this week, average response time, current open tickets, and longest-waiting ticket.', 'sort_order' => 9, 'is_active' => true],
            ['role' => 'Support', 'type' => 'quick_action', 'icon' => 'checklist',           'label' => 'New User Onboarding',          'prompt' => 'Guide me through the step-by-step process to onboard a new user: account verification, role assignment, initial configuration, and orientation tasks they need to complete.', 'sort_order' => 10, 'is_active' => true],

            // ═══════════════════════════════════════════════════════════════
            //  ACCOUNTANT (10)
            // ═══════════════════════════════════════════════════════════════
            ['role' => 'Accountant', 'type' => 'quick_action', 'icon' => 'payments',          'label' => 'Payment Reconciliation',       'prompt' => 'List all auction payments awaiting verification, sorted by amount descending. For each, show: buyer, auction title, amount, payment method, and days since payment was submitted.', 'sort_order' => 1, 'is_active' => true],
            ['role' => 'Accountant', 'type' => 'quick_action', 'icon' => 'analytics',         'label' => 'Monthly Financial Report',     'prompt' => 'Generate a month-to-date financial report with: revenue by source, outstanding receivables, commission earnings, refunds/chargebacks, and comparison to budget or prior period.', 'sort_order' => 2, 'is_active' => true],
            ['role' => 'Accountant', 'type' => 'quick_action', 'icon' => 'receipt_long',      'label' => 'Commission Reconciliation',    'prompt' => 'Reconcile commissions: show all completed auction and transfer commissions for this month, highlight any discrepancies between expected and collected amounts, and flag unpaid items.', 'sort_order' => 3, 'is_active' => true],
            ['role' => 'Accountant', 'type' => 'quick_action', 'icon' => 'subscriptions',     'label' => 'Subscription Health',          'prompt' => 'Analyze subscription metrics: active subscribers by plan, churn rate (weekly/monthly/quarterly), new signups, failed renewals, and revenue impact of churn.', 'sort_order' => 4, 'is_active' => true],
            ['role' => 'Accountant', 'type' => 'quick_action', 'icon' => 'search_insights',   'label' => 'Audit Trail Lookup',           'prompt' => 'Help me trace a specific financial transaction. I will provide a transaction ID, user ID, or auction ID. Trace the full lifecycle: creation, payment, commission, and transfer status.', 'sort_order' => 5, 'is_active' => true],
            ['role' => 'Accountant', 'type' => 'quick_action', 'icon' => 'money_off',         'label' => 'Overdue Receivables',          'prompt' => 'List all overdue payments (past payment expiry): amounts, involved parties, days overdue, and auction details. Recommend follow-up actions for each.', 'sort_order' => 6, 'is_active' => true],
            ['role' => 'Accountant', 'type' => 'quick_action', 'icon' => 'account_balance',   'label' => 'Cash Flow Forecast',           'prompt' => 'Analyze current cash position and forecast next 30 days based on: pending payments expected, upcoming subscription renewals, and estimated commission collections.', 'sort_order' => 7, 'is_active' => true],
            ['role' => 'Accountant', 'type' => 'quick_action', 'icon' => 'compare_arrows',    'label' => 'Period Comparison',            'prompt' => 'Compare this month\'s financial performance to last month and the same month last year. Highlight significant changes in revenue, expenses, and transaction volumes.', 'sort_order' => 8, 'is_active' => true],
            ['role' => 'Accountant', 'type' => 'quick_action', 'icon' => 'verified',          'label' => 'Fraud Flag Review',            'prompt' => 'Review recently flagged transactions: unusual payment patterns, duplicate payments, rapid buy-sell activity, or accounts with multiple failed payment attempts. Summarize risk level.', 'sort_order' => 9, 'is_active' => true],
            ['role' => 'Accountant', 'type' => 'quick_action', 'icon' => 'bar_chart',         'label' => 'Tax Summary Preparation',     'prompt' => 'Compile a tax preparation summary for the current period: total revenue by category, commission earnings, refund totals, and transaction counts. Include any necessary export notes.', 'sort_order' => 10, 'is_active' => true],

            // ═══════════════════════════════════════════════════════════════
            //  CUSTOMER SERVICE (10)
            // ═══════════════════════════════════════════════════════════════
            ['role' => 'Customer Service', 'type' => 'quick_action', 'icon' => 'chat',         'label' => 'Waiting Conversations',       'prompt' => 'Show me all conversations awaiting a customer service response, sorted by wait time (longest first). Include user name, subject, and last message preview.', 'sort_order' => 1, 'is_active' => true],
            ['role' => 'Customer Service', 'type' => 'quick_action', 'icon' => 'sentiment_satisfied', 'label' => 'Satisfaction Review',     'prompt' => 'Review recent user interactions and flag any conversations where the user expressed frustration, confusion, or dissatisfaction. Suggest follow-up actions.', 'sort_order' => 2, 'is_active' => true],
            ['role' => 'Customer Service', 'type' => 'quick_action', 'icon' => 'quickreply',   'label' => 'Quick Response Draft',        'prompt' => 'Help me draft a helpful response to a user inquiry. I will describe the situation and I need a clear, friendly reply that resolves their question.', 'sort_order' => 3, 'is_active' => true],
            ['role' => 'Customer Service', 'type' => 'quick_action', 'icon' => 'insights',     'label' => 'Common Questions',            'prompt' => 'Analyze the most frequent user questions from the last 7 days. Group by topic, suggest FAQ content improvements, and recommend proactive communication to reduce repeat inquiries.', 'sort_order' => 4, 'is_active' => true],
            ['role' => 'Customer Service', 'type' => 'quick_action', 'icon' => 'bar_chart',    'label' => 'My Performance',             'prompt' => 'Show my customer service metrics: conversations handled today, average first response time, average resolution time, and any unresolved conversations older than 24 hours.', 'sort_order' => 5, 'is_active' => true],
            ['role' => 'Customer Service', 'type' => 'quick_action', 'icon' => 'support',      'label' => 'Subscription Help',           'prompt' => 'Guide me through helping a user with a subscription issue: upgrade/downgrade process, failed payment troubleshooting, billing inquiry handling, or cancellation request.', 'sort_order' => 6, 'is_active' => true],
            ['role' => 'Customer Service', 'type' => 'quick_action', 'icon' => 'manage_accounts', 'label' => 'Account Issue Resolution', 'prompt' => 'Help me troubleshoot a common account issue. I will describe the problem and you will suggest step-by-step diagnostic questions and solutions.', 'sort_order' => 7, 'is_active' => true],
            ['role' => 'Customer Service', 'type' => 'quick_action', 'icon' => 'forum',         'label' => 'Trending Complaints',         'prompt' => 'What are users complaining about most this week? Identify top 3 complaint categories, quantify how many users are affected, and suggest a plan to address the root cause.', 'sort_order' => 8, 'is_active' => true],
            ['role' => 'Customer Service', 'type' => 'quick_action', 'icon' => 'volunteer_activism', 'label' => 'Win-Back Suggestions',  'prompt' => 'Identify users who showed signs of disengagement (inactive >30 days, cancelled subscription, unresolved complaint). Suggest personalized win-back messages for each segment.', 'sort_order' => 9, 'is_active' => true],
            ['role' => 'Customer Service', 'type' => 'quick_action', 'icon' => 'docs',          'label' => 'Policy Reference',            'prompt' => 'I need to look up a specific platform policy or procedure. I will describe what I need. Search available documentation and summarize the relevant policy in simple terms I can explain to a user.', 'sort_order' => 10, 'is_active' => true],

            // ═══════════════════════════════════════════════════════════════
            //  OWNER (10)
            // ═══════════════════════════════════════════════════════════════
            ['role' => 'Owner', 'type' => 'quick_action', 'icon' => 'pets',                   'label' => 'Herd Health Scan',            'prompt' => 'Analyze my entire herd\'s health status: flag any animal with abnormal vitals, overdue vaccinations, unresolved medical records, or recent health alerts. Prioritize by severity.', 'sort_order' => 1, 'is_active' => true],
            ['role' => 'Owner', 'type' => 'quick_action', 'icon' => 'gavel',                  'label' => 'Auction Strategy',            'prompt' => 'Review my active and recent auctions. Compare my pricing, bidding activity, and sell-through rate against platform averages. Suggest optimization strategies for future listings.', 'sort_order' => 2, 'is_active' => true],
            ['role' => 'Owner', 'type' => 'quick_action', 'icon' => 'device_hub',             'label' => 'Device Health Check',         'prompt' => 'Check the status of all devices on my animals: battery levels, last ping time, signal strength, and any devices that may need attention or replacement.', 'sort_order' => 3, 'is_active' => true],
            ['role' => 'Owner', 'type' => 'quick_action', 'icon' => 'assignment_turned_in',   'label' => 'Task Prioritization',         'prompt' => 'Analyze all open tasks for my farm. Prioritize them by urgency (due dates, health impact, animal welfare) and suggest an optimal order to tackle them today.', 'sort_order' => 4, 'is_active' => true],
            ['role' => 'Owner', 'type' => 'quick_action', 'icon' => 'assessment',             'label' => 'Farm Performance',            'prompt' => 'Generate a 7-day farm performance report: new animals added, tasks completed vs created, health incidents, auction activity, and compare to the previous week.', 'sort_order' => 5, 'is_active' => true],
            ['role' => 'Owner', 'type' => 'quick_action', 'icon' => 'compare',                'label' => 'Animal Comparison',           'prompt' => 'I want to compare two or more of my animals. Help me analyze their health records, activity levels, device data, vaccination status, and auction history side by side.', 'sort_order' => 6, 'is_active' => true],
            ['role' => 'Owner', 'type' => 'quick_action', 'icon' => 'notifications_active',   'label' => 'Alert Analysis',              'prompt' => 'Summarize all alerts triggered for my animals in the last 48 hours. Group by type (geofence, temperature, health, device), show affected animals, and suggest responses.', 'sort_order' => 7, 'is_active' => true],
            ['role' => 'Owner', 'type' => 'quick_action', 'icon' => 'leaderboard',            'label' => 'Vaccination Planner',         'prompt' => 'Review upcoming and overdue vaccinations for my herd. Create a prioritized vaccination schedule for the next 30 days, grouped by animal and vaccine type.', 'sort_order' => 8, 'is_active' => true],
            ['role' => 'Owner', 'type' => 'quick_action', 'icon' => 'transfer_within_a_station', 'label' => 'Transfer Readiness',      'prompt' => 'I\'m considering transferring ownership of one of my animals. Analyze which animals are good candidates based on health, auction history, current status, and any pending issues.', 'sort_order' => 9, 'is_active' => true],
            ['role' => 'Owner', 'type' => 'quick_action', 'icon' => 'savings',                'label' => 'Cost Analysis',               'prompt' => 'Analyze the costs associated with my farm operations: device subscriptions, veterinary expenses, auction fees, and transfer commissions. Suggest potential savings or optimization areas.', 'sort_order' => 10, 'is_active' => true],

            // ═══════════════════════════════════════════════════════════════
            //  MANAGER (10)
            // ═══════════════════════════════════════════════════════════════
            ['role' => 'Manager', 'type' => 'quick_action', 'icon' => 'group',                'label' => 'Team Pulse',                  'prompt' => 'Give me an overview of my team: members, their current assignments, task completion rates, recent activity, and any performance trends requiring attention.', 'sort_order' => 1, 'is_active' => true],
            ['role' => 'Manager', 'type' => 'quick_action', 'icon' => 'task_alt',             'label' => 'Workload Distribution',       'prompt' => 'Analyze how tasks are distributed across my team. Identify who is overloaded, who has capacity, and whether tasks are being assigned to the right skill sets. Suggest rebalancing if needed.', 'sort_order' => 2, 'is_active' => true],
            ['role' => 'Manager', 'type' => 'quick_action', 'icon' => 'calendar_month',       'label' => 'Weekly Ops Plan',             'prompt' => 'Based on current open tasks, upcoming deadlines, and resource availability, generate a suggested operations plan and task schedule for my team for the next 7 days.', 'sort_order' => 3, 'is_active' => true],
            ['role' => 'Manager', 'type' => 'quick_action', 'icon' => 'assignment_late',      'label' => 'At-Risk Items',               'prompt' => 'Identify tasks and projects that are behind schedule, overdue, or at risk of missing deadlines. Include assignee, original due date, and days overdue.', 'sort_order' => 4, 'is_active' => true],
            ['role' => 'Manager', 'type' => 'quick_action', 'icon' => 'trending_down',        'label' => 'Productivity Trends',         'prompt' => 'Analyze my team\'s productivity over the last 4 weeks: tasks completed per person, average completion time, and any upward or downward trends. Highlight notable changes.', 'sort_order' => 5, 'is_active' => true],
            ['role' => 'Manager', 'type' => 'quick_action', 'icon' => 'confirmation_number',  'label' => 'Resource Planning',           'prompt' => 'I need to plan resources for an upcoming operation. I will describe the scope. Help me estimate: number of people needed, skill requirements, estimated duration, and potential scheduling conflicts.', 'sort_order' => 6, 'is_active' => true],
            ['role' => 'Manager', 'type' => 'quick_action', 'icon' => 'rate_review',          'label' => 'Performance Review Prep',     'prompt' => 'Help me prepare a performance review for a team member. Analyze their completed tasks, on-time delivery rate, quality indicators, and areas where they might need development.', 'sort_order' => 7, 'is_active' => true],
            ['role' => 'Manager', 'type' => 'quick_action', 'icon' => 'conflict',             'label' => 'Conflict Resolution',         'prompt' => 'There\'s a scheduling conflict or resource contention I need to resolve. I will describe the situation. Help me analyze options and suggest a fair resolution.', 'sort_order' => 8, 'is_active' => true],
            ['role' => 'Manager', 'type' => 'quick_action', 'icon' => 'notification_important', 'label' => 'Cross-Farm Alerts',         'prompt' => 'Summarize any alerts or issues across all farms I manage: animal health alerts, device issues, pending tasks, and anything that needs my attention today.', 'sort_order' => 9, 'is_active' => true],
            ['role' => 'Manager', 'type' => 'quick_action', 'icon' => 'summarize',            'label' => 'End of Shift Report',         'prompt' => 'Generate an end-of-shift summary: tasks completed today, what\'s pending, notable events, and recommendations for the next shift or day.', 'sort_order' => 10, 'is_active' => true],

            // ═══════════════════════════════════════════════════════════════
            //  SHEPHERD (10)
            // ═══════════════════════════════════════════════════════════════
            ['role' => 'Shepherd', 'type' => 'quick_action', 'icon' => 'list_alt',            'label' => 'My Schedule',                 'prompt' => 'Show my assigned tasks for today sorted by priority and estimated duration. Include task location, animal IDs, and any preparation notes.', 'sort_order' => 1, 'is_active' => true],
            ['role' => 'Shepherd', 'type' => 'quick_action', 'icon' => 'location_on',         'label' => 'Herd Location Map',            'prompt' => 'Where are my assigned animals right now? Summarize their latest GPS positions, highlight any animals outside their designated geofence, and show distances from expected locations.', 'sort_order' => 2, 'is_active' => true],
            ['role' => 'Shepherd', 'type' => 'quick_action', 'icon' => 'warning_amber',       'label' => 'Urgent Attention',             'prompt' => 'Which animals need my immediate attention? Check health alerts, abnormal vitals, geofence breaches, and device warnings. Prioritize by severity and suggest a response order.', 'sort_order' => 3, 'is_active' => true],
            ['role' => 'Shepherd', 'type' => 'quick_action', 'icon' => 'pending_actions',     'label' => 'Overdue Work',                'prompt' => 'List all my overdue or incomplete tasks sorted by how overdue they are. For each, show: original due date, animal involved, task type, and reason it\'s still open if noted.', 'sort_order' => 4, 'is_active' => true],
            ['role' => 'Shepherd', 'type' => 'quick_action', 'icon' => 'direction_run',       'label' => 'Efficient Route',             'prompt' => 'Plan the most efficient route to complete my today\'s tasks based on animal locations. Optimize for distance and priority so I can check on all animals that need attention.', 'sort_order' => 5, 'is_active' => true],
            ['role' => 'Shepherd', 'type' => 'quick_action', 'icon' => 'battery_alert',       'label' => 'Low Battery Check',           'prompt' => 'Which animals have devices with low battery (&lt;20%)? List device IDs, current battery level, last ping time, and animal details so I can plan replacements.', 'sort_order' => 6, 'is_active' => true],
            ['role' => 'Shepherd', 'type' => 'quick_action', 'icon' => 'thermostat',          'label' => 'Temperature Check',           'prompt' => 'Scan all my animals for abnormal body temperature readings. Flag anything outside normal range, show the trend (rising/falling), and suggest which need medical attention.', 'sort_order' => 7, 'is_active' => true],
            ['role' => 'Shepherd', 'type' => 'quick_action', 'icon' => 'assignment_return',   'label' => 'Handover Notes',              'prompt' => 'Generate end-of-shift handover notes for the next shepherd: completed tasks, pending items, animals of concern, and anything unusual observed today.', 'sort_order' => 8, 'is_active' => true],
            ['role' => 'Shepherd', 'type' => 'quick_action', 'icon' => 'group_work',          'label' => 'Group Status',                'prompt' => 'Show me the status of each animal group I\'m responsible for: group size, animals in/out of geofence, recent alerts, and any group-level health concerns.', 'sort_order' => 9, 'is_active' => true],
            ['role' => 'Shepherd', 'type' => 'quick_action', 'icon' => 'fact_check',          'label' => 'Quick Animal ID',             'prompt' => 'Help me look up a specific animal. I will provide a name, tag number, or ID. Show me: species, location, latest vitals, today\'s tasks, and any recent alerts.', 'sort_order' => 10, 'is_active' => true],

            // ═══════════════════════════════════════════════════════════════
            //  DOCTOR (10)
            // ═══════════════════════════════════════════════════════════════
            ['role' => 'Doctor', 'type' => 'quick_action', 'icon' => 'vaccines',              'label' => 'Vaccination Roundup',         'prompt' => 'List all vaccinations due in the next 14 days grouped by priority (overdue first, then due this week, then next week). Include animal details and vaccine type for each.', 'sort_order' => 1, 'is_active' => true],
            ['role' => 'Doctor', 'type' => 'quick_action', 'icon' => 'monitor_heart',         'label' => 'Critical Vitals',             'prompt' => 'Show all animals with abnormal vital signs (temperature, heart rate, or other metrics outside normal range). Flag the most critical cases and suggest immediate next steps.', 'sort_order' => 2, 'is_active' => true],
            ['role' => 'Doctor', 'type' => 'quick_action', 'icon' => 'healing',               'label' => 'Treatment Plan Review',       'prompt' => 'Review all active treatment plans. Identify animals where treatment is not on schedule, outcomes are not improving, or follow-up is overdue. Recommend adjustments.', 'sort_order' => 3, 'is_active' => true],
            ['role' => 'Doctor', 'type' => 'quick_action', 'icon' => 'trending_up',           'label' => 'Herd Health Trends',          'prompt' => 'Analyze herd health trends over the last 30 days: most common diagnoses, treatment success rates, seasonal patterns, and any emerging health concerns across the population.', 'sort_order' => 4, 'is_active' => true],
            ['role' => 'Doctor', 'type' => 'quick_action', 'icon' => 'note_add',              'label' => 'Medical Record Draft',        'prompt' => 'Help me draft a medical record for an animal. I will describe the examination findings, diagnosis, and treatment administered. Format it as a professional medical note.', 'sort_order' => 5, 'is_active' => true],
            ['role' => 'Doctor', 'type' => 'quick_action', 'icon' => 'history',               'label' => 'Patient History',             'prompt' => 'Compile a complete medical history for a specific animal. Include: past diagnoses, treatments, vaccinations, weight trends, and any recurring health issues.', 'sort_order' => 6, 'is_active' => true],
            ['role' => 'Doctor', 'type' => 'quick_action', 'icon' => 'warning',              'label' => 'Disease Risk Assessment',     'prompt' => 'Assess disease risk across the herd based on recent symptoms, environmental factors, and vaccination coverage. Flag any animals or groups at elevated risk and suggest preventive measures.', 'sort_order' => 7, 'is_active' => true],
            ['role' => 'Doctor', 'type' => 'quick_action', 'icon' => 'calendar_today',        'label' => 'Follow-Up Schedule',          'prompt' => 'Generate a follow-up schedule for animals that need re-examination. Group by urgency (immediate, 24h, 48h, 7 days) and include reason for follow-up and previous treatment summary.', 'sort_order' => 8, 'is_active' => true],
            ['role' => 'Doctor', 'type' => 'quick_action', 'icon' => 'biotech',               'label' => 'Prescription Check',          'prompt' => 'Review recent prescriptions and treatments. Check for: expired medications, dosage anomalies, conflicting treatments, and animals that may need prescription updates.', 'sort_order' => 9, 'is_active' => true],
            ['role' => 'Doctor', 'type' => 'quick_action', 'icon' => 'summarize',             'label' => 'Daily Health Brief',          'prompt' => 'Generate a concise daily health briefing: new cases, critical patients, procedures scheduled, vaccinations administered today, and any health alerts triggered in the last 24 hours.', 'sort_order' => 10, 'is_active' => true],
        ];

        foreach ($actions as $action) {
            if (!array_key_exists('language', $action)) {
                $action['language'] = 'en';
            }
            AiQuickAction::create($action);
        }

        $this->command->info('  ' . count($actions) . ' AI quick actions seeded (en)');

        $this->createLanguageVariants();

        $this->command->info('  Language variants created for ar, ur, eu');
    }

    protected function createLanguageVariants(): void
    {
        $labelTranslations = [
            'en' => [
                // Admin
                'Platform Pulse' => 'Platform Pulse',
                'Approval Queue' => 'Approval Queue',
                'Growth Trends' => 'Growth Trends',
                'Revenue Deep Dive' => 'Revenue Deep Dive',
                'System Health' => 'System Health',
                'Staff Performance' => 'Staff Performance',
                'User Demographics' => 'User Demographics',
                'Commission Audit' => 'Commission Audit',
                'Risk Assessment' => 'Risk Assessment',
                'Engagement Audit' => 'Engagement Audit',
                'Weekly Ops Brief' => 'Weekly Ops Brief',
                'Device Fleet Status' => 'Device Fleet Status',
                // Support
                'Priority Queue' => 'Priority Queue',
                'User Lookup' => 'User Lookup',
                'Ticket Patterns' => 'Ticket Patterns',
                'SLA Breach Watch' => 'SLA Breach Watch',
                'Draft Response' => 'Draft Response',
                'Ticket Summary' => 'Ticket Summary',
                'Knowledge Search' => 'Knowledge Search',
                'Escalation Helper' => 'Escalation Helper',
                'My Stats' => 'My Stats',
                'New User Onboarding' => 'New User Onboarding',
                // Accountant
                'Payment Reconciliation' => 'Payment Reconciliation',
                'Monthly Financial Report' => 'Monthly Financial Report',
                'Commission Reconciliation' => 'Commission Reconciliation',
                'Subscription Health' => 'Subscription Health',
                'Audit Trail Lookup' => 'Audit Trail Lookup',
                'Overdue Receivables' => 'Overdue Receivables',
                'Cash Flow Forecast' => 'Cash Flow Forecast',
                'Period Comparison' => 'Period Comparison',
                'Fraud Flag Review' => 'Fraud Flag Review',
                'Tax Summary Preparation' => 'Tax Summary Preparation',
                // Customer Service
                'Waiting Conversations' => 'Waiting Conversations',
                'Satisfaction Review' => 'Satisfaction Review',
                'Quick Response Draft' => 'Quick Response Draft',
                'Common Questions' => 'Common Questions',
                'My Performance' => 'My Performance',
                'Subscription Help' => 'Subscription Help',
                'Account Issue Resolution' => 'Account Issue Resolution',
                'Trending Complaints' => 'Trending Complaints',
                'Win-Back Suggestions' => 'Win-Back Suggestions',
                'Policy Reference' => 'Policy Reference',
                // Owner
                'Herd Health Scan' => 'Herd Health Scan',
                'Auction Strategy' => 'Auction Strategy',
                'Device Health Check' => 'Device Health Check',
                'Task Prioritization' => 'Task Prioritization',
                'Farm Performance' => 'Farm Performance',
                'Animal Comparison' => 'Animal Comparison',
                'Alert Analysis' => 'Alert Analysis',
                'Vaccination Planner' => 'Vaccination Planner',
                'Transfer Readiness' => 'Transfer Readiness',
                'Cost Analysis' => 'Cost Analysis',
                // Manager
                'Team Pulse' => 'Team Pulse',
                'Workload Distribution' => 'Workload Distribution',
                'Weekly Ops Plan' => 'Weekly Ops Plan',
                'At-Risk Items' => 'At-Risk Items',
                'Productivity Trends' => 'Productivity Trends',
                'Resource Planning' => 'Resource Planning',
                'Performance Review Prep' => 'Performance Review Prep',
                'Conflict Resolution' => 'Conflict Resolution',
                'Cross-Farm Alerts' => 'Cross-Farm Alerts',
                'End of Shift Report' => 'End of Shift Report',
                // Shepherd
                'My Schedule' => 'My Schedule',
                'Herd Location Map' => 'Herd Location Map',
                'Urgent Attention' => 'Urgent Attention',
                'Overdue Work' => 'Overdue Work',
                'Efficient Route' => 'Efficient Route',
                'Low Battery Check' => 'Low Battery Check',
                'Temperature Check' => 'Temperature Check',
                'Handover Notes' => 'Handover Notes',
                'Group Status' => 'Group Status',
                'Quick Animal ID' => 'Quick Animal ID',
                // Doctor
                'Vaccination Roundup' => 'Vaccination Roundup',
                'Critical Vitals' => 'Critical Vitals',
                'Treatment Plan Review' => 'Treatment Plan Review',
                'Herd Health Trends' => 'Herd Health Trends',
                'Medical Record Draft' => 'Medical Record Draft',
                'Patient History' => 'Patient History',
                'Disease Risk Assessment' => 'Disease Risk Assessment',
                'Follow-Up Schedule' => 'Follow-Up Schedule',
                'Prescription Check' => 'Prescription Check',
                'Daily Health Brief' => 'Daily Health Brief',
            ],
            'ar' => [
                'Platform Pulse' => 'نبض المنصة',
                'Approval Queue' => 'قائمة الموافقات',
                'Growth Trends' => 'اتجاهات النمو',
                'Revenue Deep Dive' => 'تحليل الإيرادات',
                'System Health' => 'صحة النظام',
                'Staff Performance' => 'أداء الموظفين',
                'User Demographics' => 'إحصائيات المستخدمين',
                'Commission Audit' => 'تدقيق العمولات',
                'Risk Assessment' => 'تقييم المخاطر',
                'Engagement Audit' => 'تدقيق التفاعل',
                'Weekly Ops Brief' => 'ملخص أسبوعي',
                'Device Fleet Status' => 'حالة أسطول الأجهزة',
                'Priority Queue' => 'قائمة الأولويات',
                'User Lookup' => 'البحث عن مستخدم',
                'Ticket Patterns' => 'أنماط التذاكر',
                'SLA Breach Watch' => 'مراقبة خرق SLA',
                'Draft Response' => 'مسودة رد',
                'Ticket Summary' => 'ملخص التذكرة',
                'Knowledge Search' => 'البحث في المعرفة',
                'Escalation Helper' => 'مساعد التصعيد',
                'My Stats' => 'إحصائياتي',
                'New User Onboarding' => 'توجيه مستخدم جديد',
                'Payment Reconciliation' => 'تسوية المدفوعات',
                'Monthly Financial Report' => 'تقرير مالي شهري',
                'Commission Reconciliation' => 'تسوية العمولات',
                'Subscription Health' => 'صحة الاشتراكات',
                'Audit Trail Lookup' => 'تتبع مسار التدقيق',
                'Overdue Receivables' => 'المستحقات المتأخرة',
                'Cash Flow Forecast' => 'توقعات التدفق النقدي',
                'Period Comparison' => 'مقارنة الفترات',
                'Fraud Flag Review' => 'مراجعة علامات الاحتيال',
                'Tax Summary Preparation' => 'تحضير ملخص الضرائب',
                'Waiting Conversations' => 'المحادثات المنتظرة',
                'Satisfaction Review' => 'مراجعة الرضا',
                'Quick Response Draft' => 'مسودة رد سريع',
                'Common Questions' => 'الأسئلة الشائعة',
                'My Performance' => 'أدائي',
                'Subscription Help' => 'مساعدة الاشتراك',
                'Account Issue Resolution' => 'حل مشكلات الحساب',
                'Trending Complaints' => 'الشكاوى الرائجة',
                'Win-Back Suggestions' => 'اقتراحات الاستعادة',
                'Policy Reference' => 'مرجع السياسات',
                'Herd Health Scan' => 'فحص صحة القطيع',
                'Auction Strategy' => 'استراتيجية المزاد',
                'Device Health Check' => 'فحص صحة الجهاز',
                'Task Prioritization' => 'تحديد أولويات المهام',
                'Farm Performance' => 'أداء المزرعة',
                'Animal Comparison' => 'مقارنة الحيوانات',
                'Alert Analysis' => 'تحليل التنبيهات',
                'Vaccination Planner' => 'مخطط التطعيمات',
                'Transfer Readiness' => 'جاهزية النقل',
                'Cost Analysis' => 'تحليل التكاليف',
                'Team Pulse' => 'نبض الفريق',
                'Workload Distribution' => 'توزيع عبء العمل',
                'Weekly Ops Plan' => 'خطة أسبوعية',
                'At-Risk Items' => 'العناصر المعرضة للخطر',
                'Productivity Trends' => 'اتجاهات الإنتاجية',
                'Resource Planning' => 'تخطيط الموارد',
                'Performance Review Prep' => 'تحضير تقييم الأداء',
                'Conflict Resolution' => 'حل النزاعات',
                'Cross-Farm Alerts' => 'تنبيهات عبر المزارع',
                'End of Shift Report' => 'تقرير نهاية المناوبة',
                'My Schedule' => 'جدولي',
                'Herd Location Map' => 'خريطة موقع القطيع',
                'Urgent Attention' => 'اهتمام عاجل',
                'Overdue Work' => 'عمل متأخر',
                'Efficient Route' => 'طريق فعال',
                'Low Battery Check' => 'فحص البطارية المنخفضة',
                'Temperature Check' => 'فحص درجة الحرارة',
                'Handover Notes' => 'ملاحظات التسليم',
                'Group Status' => 'حالة المجموعة',
                'Quick Animal ID' => 'معرف الحيوان السريع',
                'Vaccination Roundup' => 'جولة التطعيمات',
                'Critical Vitals' => 'العلامات الحيوية الحرجة',
                'Treatment Plan Review' => 'مراجعة خطة العلاج',
                'Herd Health Trends' => 'اتجاهات صحة القطيع',
                'Medical Record Draft' => 'مسودة سجل طبي',
                'Patient History' => 'تاريخ المريض',
                'Disease Risk Assessment' => 'تقييم مخاطر الأمراض',
                'Follow-Up Schedule' => 'جدول المتابعة',
                'Prescription Check' => 'فحص الوصفات الطبية',
                'Daily Health Brief' => 'موجز صحي يومي',
            ],
            'ur' => [
                'Platform Pulse' => 'پلیٹ فارم کی نبض',
                'Approval Queue' => 'منظوری کی قطار',
                'Growth Trends' => 'ترقی کے رجحانات',
                'Revenue Deep Dive' => 'آمدنی کا گہرائی سے تجزیہ',
                'System Health' => 'سسٹم کی صحت',
                'Staff Performance' => 'عملے کی کارکردگی',
                'User Demographics' => 'صارفین کی آبادیات',
                'Commission Audit' => 'کمیشن آڈٹ',
                'Risk Assessment' => 'خطرے کا جائزہ',
                'Engagement Audit' => 'مصروفیت کا جائزہ',
                'Weekly Ops Brief' => 'ہفتہ وار آپریشنز بریف',
                'Device Fleet Status' => 'آلات کی حالت',
                'Priority Queue' => 'ترجیحی قطار',
                'User Lookup' => 'صارف تلاش کریں',
                'Ticket Patterns' => 'ٹکٹ کے پیٹرن',
                'SLA Breach Watch' => 'SLA کی خلاف ورزی کی نگرانی',
                'Draft Response' => 'مسودہ جواب',
                'Ticket Summary' => 'ٹکٹ کا خلاصہ',
                'Knowledge Search' => 'علم کی تلاش',
                'Escalation Helper' => 'سیڑھی بڑھانے میں مدد',
                'My Stats' => 'میرے اعدادوشمار',
                'New User Onboarding' => 'نئے صارف کی رہنمائی',
                'Payment Reconciliation' => 'ادائیگیوں کی مطابقت',
                'Monthly Financial Report' => 'ماہانہ مالی رپورٹ',
                'Commission Reconciliation' => 'کمیشن کی مطابقت',
                'Subscription Health' => 'سبسکرپشن کی صحت',
                'Audit Trail Lookup' => 'آڈٹ ٹریل تلاش',
                'Overdue Receivables' => 'زیر التواء وصولیاں',
                'Cash Flow Forecast' => 'نقد بہاؤ کی پیش گوئی',
                'Period Comparison' => 'مدت کا موازنہ',
                'Fraud Flag Review' => 'دھوکہ دہی کے جھنڈوں کا جائزہ',
                'Tax Summary Preparation' => 'ٹیکس خلاصہ کی تیاری',
                'Waiting Conversations' => 'زیر التواء گفتگو',
                'Satisfaction Review' => 'اطمینان کا جائزہ',
                'Quick Response Draft' => 'فوری جواب کا مسودہ',
                'Common Questions' => 'عام سوالات',
                'My Performance' => 'میری کارکردگی',
                'Subscription Help' => 'سبسکرپشن مدد',
                'Account Issue Resolution' => 'اکاؤنٹ کے مسئلے کا حل',
                'Trending Complaints' => 'مشہور شکایات',
                'Win-Back Suggestions' => 'واپسی کی تجاویز',
                'Policy Reference' => 'پالیسی حوالہ',
                'Herd Health Scan' => 'ریوڑ کی صحت کا اسکین',
                'Auction Strategy' => 'نیلامی کی حکمت عملی',
                'Device Health Check' => 'آلے کی صحت کا چیک',
                'Task Prioritization' => 'کاموں کی ترجیح',
                'Farm Performance' => 'فارم کی کارکردگی',
                'Animal Comparison' => 'جانوروں کا موازنہ',
                'Alert Analysis' => 'الرٹ کا تجزیہ',
                'Vaccination Planner' => 'ویکسینیشن پلانر',
                'Transfer Readiness' => 'منتقلی کی تیاری',
                'Cost Analysis' => 'لاگت کا تجزیہ',
                'Team Pulse' => 'ٹیم کی نبض',
                'Workload Distribution' => 'کام کے بوجھ کی تقسیم',
                'Weekly Ops Plan' => 'ہفتہ وار آپریشن پلان',
                'At-Risk Items' => 'خطرے والی اشیاء',
                'Productivity Trends' => 'پیداواری رجحانات',
                'Resource Planning' => 'وسائل کی منصوبہ بندی',
                'Performance Review Prep' => 'کارکردگی کے جائزے کی تیاری',
                'Conflict Resolution' => 'تنازعہ کا حل',
                'Cross-Farm Alerts' => 'کراس فارم الرٹس',
                'End of Shift Report' => 'شفٹ کے اختتام کی رپورٹ',
                'My Schedule' => 'میرا شیڈول',
                'Herd Location Map' => 'ریوڑ کے مقام کا نقشہ',
                'Urgent Attention' => 'فوری توجہ',
                'Overdue Work' => 'زیر التواء کام',
                'Efficient Route' => 'موثر راستہ',
                'Low Battery Check' => 'کم بیٹری کا چیک',
                'Temperature Check' => 'درجہ حرارت کا چیک',
                'Handover Notes' => 'حوالگی کے نوٹس',
                'Group Status' => 'گروپ کی حالت',
                'Quick Animal ID' => 'فوری جانور کی شناخت',
                'Vaccination Roundup' => 'ویکسینیشن راؤنڈ اپ',
                'Critical Vitals' => 'اہم علامات',
                'Treatment Plan Review' => 'علاج کے منصوبے کا جائزہ',
                'Herd Health Trends' => 'ریوڑ کی صحت کے رجحانات',
                'Medical Record Draft' => 'میڈیکل ریکارڈ کا مسودہ',
                'Patient History' => 'مریض کی تاریخ',
                'Disease Risk Assessment' => 'بیماری کے خطرے کا جائزہ',
                'Follow-Up Schedule' => 'فالو اپ شیڈول',
                'Prescription Check' => 'نسخے کا چیک',
                'Daily Health Brief' => 'یومیہ صحت کا خلاصہ',
            ],
            'eu' => [
                'Platform Pulse' => 'Plataformaren pultsua',
                'Approval Queue' => 'Onartzeko ilara',
                'Growth Trends' => 'Hazkunde joerak',
                'Revenue Deep Dive' => 'Diru-sarreren azterketa',
                'System Health' => 'Sistemaren osasuna',
                'Staff Performance' => 'Langileen errendimendua',
                'User Demographics' => 'Erabiltzaileen demografia',
                'Commission Audit' => 'Komisioen auditoria',
                'Risk Assessment' => 'Arriskuen ebaluazioa',
                'Engagement Audit' => 'Konpromisoaren auditoria',
                'Weekly Ops Brief' => 'Astearteko laburpena',
                'Device Fleet Status' => 'Gailuen egoera',
                'Priority Queue' => 'Lehentasun ilara',
                'User Lookup' => 'Erabiltzaile bilaketa',
                'Ticket Patterns' => 'Txantiloi ereduak',
                'SLA Breach Watch' => 'SLA hausturaren kontrola',
                'Draft Response' => 'Erantzun zirriborroa',
                'Ticket Summary' => 'Txantiloiaren laburpena',
                'Knowledge Search' => 'Jakintza bilaketa',
                'Escalation Helper' => 'Eskalatze laguntzailea',
                'My Stats' => 'Nire estatistikak',
                'New User Onboarding' => 'Erabiltzaile berriaren orientazioa',
                'Payment Reconciliation' => 'Ordainketen bateratzea',
                'Monthly Financial Report' => 'Hileko finantza txostena',
                'Commission Reconciliation' => 'Komisioen bateratzea',
                'Subscription Health' => 'Harpidetzen osasuna',
                'Audit Trail Lookup' => 'Auditoretza bidearen bilaketa',
                'Overdue Receivables' => 'Ordaindu gabeko kobratzekoak',
                'Cash Flow Forecast' => 'Kaudimenaren aurreikuspena',
                'Period Comparison' => 'Aldien konparazioa',
                'Fraud Flag Review' => 'Iruzur seinaleen berrikuspena',
                'Tax Summary Preparation' => 'Zerga laburpenaren prestaketa',
                'Waiting Conversations' => 'Itxarote elkarrizketak',
                'Satisfaction Review' => 'Gogobetetasunaren berrikuspena',
                'Quick Response Draft' => 'Erantzun azkarraren zirriborroa',
                'Common Questions' => 'Ohiko galderak',
                'My Performance' => 'Nire errendimendua',
                'Subscription Help' => 'Harpidetzen laguntza',
                'Account Issue Resolution' => 'Kontu arazoen konponbidea',
                'Trending Complaints' => 'Kexa gorenak',
                'Win-Back Suggestions' => 'Berreskuratze iradokizunak',
                'Policy Reference' => 'Politiken erreferentzia',
                'Herd Health Scan' => 'Aldearen osasun miaketa',
                'Auction Strategy' => 'Enkanteen estrategia',
                'Device Health Check' => 'Gailuaren osasun egiaztapena',
                'Task Prioritization' => 'Atazen lehentasuna',
                'Farm Performance' => 'Baserriaren errendimendua',
                'Animal Comparison' => 'Animalien konparazioa',
                'Alert Analysis' => 'Alertaren azterketa',
                'Vaccination Planner' => 'Txertaketa planifikatzailea',
                'Transfer Readiness' => 'Transferentziarako prestutasuna',
                'Cost Analysis' => 'Kostuen analisia',
                'Team Pulse' => 'Taldearen pultsua',
                'Workload Distribution' => 'Lan kargaren banaketa',
                'Weekly Ops Plan' => 'Astearteko lan plana',
                'At-Risk Items' => 'Arriskuan dauden elementuak',
                'Productivity Trends' => 'Produktibitate joerak',
                'Resource Planning' => 'Baliabideen plangintza',
                'Performance Review Prep' => 'Errendimendu berrikuspenaren prestaketa',
                'Conflict Resolution' => 'Gatazken konponbidea',
                'Cross-Farm Alerts' => 'Baserri arteko alertak',
                'End of Shift Report' => 'Txandaren amaierako txostena',
                'My Schedule' => 'Nire egutegia',
                'Herd Location Map' => 'Aldearen kokapen mapa',
                'Urgent Attention' => 'Premiazko arreta',
                'Overdue Work' => 'Atzeratutako lana',
                'Efficient Route' => 'Ibilbide eraginkorra',
                'Low Battery Check' => 'Bateria baxuaren egiaztapena',
                'Temperature Check' => 'Tenperaturaren egiaztapena',
                'Handover Notes' => 'Entregatze oharrak',
                'Group Status' => 'Taldearen egoera',
                'Quick Animal ID' => 'Animalia ID azkarra',
                'Vaccination Roundup' => 'Txertaketa biribilketa',
                'Critical Vitals' => 'Seinale bital kritikoak',
                'Treatment Plan Review' => 'Tratamendu planaren berrikuspena',
                'Herd Health Trends' => 'Aldearen osasun joerak',
                'Medical Record Draft' => 'Erregistro medikoaren zirriborroa',
                'Patient History' => 'Pazientearen historia',
                'Disease Risk Assessment' => 'Gaixotasun arriskuaren ebaluazioa',
                'Follow-Up Schedule' => 'Jarraipen egutegia',
                'Prescription Check' => 'Errezeten egiaztapena',
                'Daily Health Brief' => 'Eguneko osasun laburpena',
            ],
        ];

        $enActions = AiQuickAction::where('language', 'en')->where('role', '!=', null)->get();

        foreach (['ar', 'ur', 'eu'] as $lang) {
            foreach ($enActions as $action) {
                $translatedLabel = $labelTranslations[$lang][$action->label] ?? $action->label;
                AiQuickAction::create([
                    'role' => $action->role,
                    'language' => $lang,
                    'type' => $action->type,
                    'icon' => $action->icon,
                    'label' => $translatedLabel,
                    'prompt' => $action->prompt,
                    'sort_order' => $action->sort_order,
                    'is_active' => $action->is_active,
                ]);
            }
        }
    }
}
