#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

error_reporting(E_ALL & ~E_DEPRECATED);
ini_set('display_errors', '0');

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
