[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["php84", "composer", "nodejs_22", "nodePackages.npm"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-scripts --ignore-platform-reqs --no-interaction"
]

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
