/** @type {import('tailwindcss').Config} */
export default {
  content: ['./resources/js/**/*.{js,jsx}', './resources/views/**/*.blade.php'],
  theme: {
    extend: {
      colors: {
        primary: '#002819',
        'primary-container': '#06402B',
        secondary: '#4f6357',
        'secondary-container': '#cfe5d6',
        tertiary: '#735c00',
        'tertiary-fixed': '#ffe088',
        background: '#fafaf5',
        surface: {
          dim: '#dadad5',
          container: '#eeeee9',
          'container-high': '#e8e8e3',
          'container-highest': '#e3e3de',
          'container-low': '#f4f4ef',
          'container-lowest': '#ffffff',
          bright: '#fafaf5',
          variant: '#e3e3de',
          tint: '#356850',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#77ac90',
        'on-primary-fixed': '#002114',
        'on-primary-fixed-variant': '#1b503a',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#53675c',
        'on-secondary-fixed': '#0c1f16',
        'on-secondary-fixed-variant': '#384b40',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#4e3d00',
        'on-tertiary-fixed': '#241a00',
        'on-tertiary-fixed-variant': '#574500',
        'on-background': '#1a1c19',
        'on-surface': '#1a1c19',
        'on-surface-variant': '#404943',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        outline: '#717973',
        'outline-variant': '#c0c9c1',
        inverse: {
          surface: '#2f312e',
          'on-surface': '#f1f1ec',
          primary: '#9cd2b5',
        },
        'primary-fixed': '#b8efd0',
        'primary-fixed-dim': '#9cd2b5',
        'secondary-fixed': '#d2e8d9',
        'secondary-fixed-dim': '#b6ccbe',
        'tertiary-fixed-dim': '#e9c349',
      },
      fontFamily: {
        headline: ['Manrope'],
        body: ['Inter'],
        label: ['Inter'],
      },
    },
  },
};
