<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;

class PageSeeder extends Seeder
{
    public function run(): void
    {
        $pages = [
            [
                'slug' => 'privacy',
                'title' => 'Privacy Policy',
                'content' => 'Your privacy is important to us. This Privacy Policy outlines how we collect, use, and protect your personal information when you use our platform.

We collect information you provide directly, such as your name, email address, and phone number. We also collect data generated by your use of the platform, including animal tracking data and device information.

Your data is used to provide and improve our services, communicate with you, and ensure the security of our platform. We do not share your personal information with third parties except as required by law or with your explicit consent.

We implement industry-standard security measures to protect your data. You have the right to access, update, or delete your personal information at any time.

For questions about this policy, please contact your account administrator.',
                'is_published' => true,
            ],
            [
                'slug' => 'terms',
                'title' => 'Terms of Service',
                'content' => 'By using our platform, you agree to these Terms of Service. Please read them carefully.

You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.

You agree to use the platform only for lawful purposes and in accordance with these terms. You may not use the platform to violate any laws or regulations.

We reserve the right to suspend or terminate accounts that violate these terms or engage in prohibited activities.

The platform is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the platform.

We may update these terms from time to time. Continued use of the platform after changes constitutes acceptance of the new terms.',
                'is_published' => true,
            ],
            [
                'slug' => 'contact',
                'title' => 'Contact Us',
                'content' => 'We\'d love to hear from you. Whether you have a question about our services, need technical support, or want to provide feedback, our team is here to help.

You can reach us by sending a message through the contact form on this page, or by creating a support ticket from the Messages section.

Our support team typically responds within 24 hours during business days.

For urgent matters, please contact your account administrator directly.',
                'is_published' => true,
            ],
        ];

        foreach ($pages as $data) {
            Page::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }

        $this->command->info('Created/updated ' . count($pages) . ' static pages.');
    }
}
